services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "composer install &&
            make start-app"
    networks:
      - default

  database:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
    ports:
      - 54320:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default